
keys = [*range(0,25,1)]
vals = list('abcdefghijklmnopqrstuvwxyz')
pico_to_char = {keys[i]:vals[i] for i in range(len(keys))}


print(keys)
print(vals)

print(pico_to_char.values)

#this will be in a different file/autogenerated from json

chords = {'ho':'hello', 'dw': 'world'}

def getChord(pico_output):
    temp = ''
    for out in pico_output:
        temp += pico_to_char[out]
        #temp += pico_to_char.get[out]
    if ''.join(sorted(temp)) in chords:
        return chords.get(''.join(sorted(temp)))
    else:
        return temp

testing_arr = []

for x in range(1):
    num = input("")
    testing_arr.append(num)

print(getChord(testing_arr))



